# fly.toml file generated for myivo on 2022-05-23T09:56:13+01:00

app = "myivo"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  RUST_LOG = "debug"

[[files]]
  guest_path = "/root/keys/AuthKey.p8"
  secret_name = "APPLE_DEVELOPER_TOKEN_AUTH_KEY"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
